theme: jekyll-theme-minimal
title: MCPL Union - AFSCME 2802
description: The Monroe County Public Library organized with AFSCME in 2008 to provide support to library workers. Contact us at mcplunion@gmail.com
